version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: aegis-postgres
    environment:
      POSTGRES_DB: aegisai
      POSTGRES_USER: aegis
      POSTGRES_PASSWORD: aegis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: aegis-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kafka:
    image: apache/kafka:latest
    container_name: aegis-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: aegis-backend
    environment:
      DATABASE_URL: postgresql://aegis:aegis@postgres:5432/aegisai
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_INDEX: incidents
      KAFKA_BOOTSTRAP: kafka:29092
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
      - kafka

  log-consumer:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: aegis-log-consumer
    command: ["python", "-m", "services.log_consumer"]
    environment:
      DATABASE_URL: postgresql://aegis:aegis@postgres:5432/aegisai
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_INDEX: incidents
      KAFKA_BOOTSTRAP: kafka:29092
    depends_on:
      - postgres
      - elasticsearch
      - kafka

volumes:
  postgres_data:
  es_data:

